### ISSUE TITLE
Async messages

### ISSUE THREAD

**Issue by abelsson** [abelsson/androkom#6]
It should be possible to send and receive async messages. Preferably it should be possible to receive them when the client ui isn't open either.

**Comment by johan-martenson** [comment]
Ideally this would behave like when a gmail message is received. A notification is added and when it's clicked it launches the view async message activity(?)

**Comment by johan-martenson** [comment]
By the way, I have prototyped the code for adding support for async messages to lattekom. If we're going to switch to Rasmus' lattekom implementation we should do so before I implement it in that lattekom.

**Comment by jonasgit** [comment]
I would say this is in the repository now.
